name: Instagram to Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # Alle 30 Minuten

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python -m playwright install

    - name: Restore Instagram session from secret
      run: |
        mkdir -p ~/.config/instaloader
        echo "${{ secrets.IG_SESSION_COOKIE }}" | base64 -d > ~/.config/instaloader/session-user25180_u

    - name: Run bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_LOG_CHAT_ID: ${{ secrets.TELEGRAM_LOG_CHAT_ID }}
        TARGET_USERNAME: ${{ secrets.TARGET_USERNAME }}
      run: |
        python3 bot.py
